sudo: false

language: generic

matrix:
  include:
    - env: BUILD=tinc CABALVER=1.22 GHCVER=7.10.3
      compiler: ": #tinc 7.10.3"
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3,happy-1.19.5], sources: [hvr-ghc]}}
    - env: BUILD=tinc CABALVER=1.24 GHCVER=8.0.1
      compiler: ": #tinc 8.0.1"
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.1,happy-1.19.5], sources: [hvr-ghc]}}
    - env: BUILD=tinc CABALVER=2.0 GHCVER=8.2.1
      compiler: ": #tinc 8.2.1"
      addons: {apt: {packages: [cabal-install-2.0,ghc-8.2.1,happy-1.19.5], sources: [hvr-ghc]}}
    - env: BUILD=stack GHCVER=8.2.1 STACK_YAML=stack.yaml
      compiler: ": #stack 8.2.1"
      addons: {apt: {packages: [ghc-8.2.1,happy-1.19.5], sources: [hvr-ghc]}}
    - env: BUILD=stack STACK_YAML=stack.yaml
      compiler: ": #stack 8.2.1 osx"
      os: osx

before_install:
  - unset CC
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/happy/1.19.5/bin:$PATH
  - ./.travis-setup.sh
  - ghc --version || stack exec -- ghc --version
  - happy --version || true
  - cabal --version || true
  - stack --version || true
  - tinc --version || true

install:
  - case "$BUILD" in
      tinc)
        tinc;;
      stack)
        stack --no-terminal test --only-dependencies;;
    esac

script:
  - case "$BUILD" in
      tinc)
        cabal configure --enable-tests --ghc-options=-Werror --disable-optimization && cabal build && cabal test;;
      stack)
        stack --no-terminal test --haddock --no-haddock-deps;;
    esac

after_success:
  - > # Upload tarball to Hackage.
    mkdir -p "$HOME/.stack/upload"
    && echo "{ \"username\": \"$HACKAGE_USERNAME\", \"password\": \"$HACKAGE_PASSWORD\" }" > "$HOME/.stack/uploads/credentials.json"
    && if test -n "$TRAVIS_TAG"; then stack upload .; fi
  - > # Upload binary to GitHub.
    curl --location https://github.com/tfausak/github-release/releases/download/1.1.3/github-release-1.1.3-linux.gz --output github-release.gz
    && gunzip github-release.gz
    && chmod +x github-release
    && ./github-release version
    && if test -n "$TRAVIS_TAG"
      ; then ./github-release upload
        --token "$GITHUB_TOKEN"
        --repo "$TRAVIS_REPO_SLUG"
        --tag "$TRAVIS_TAG"
        --file "$(stack exec which hpack)"
        --name "hpack-$TRAVIS_TAG-linux"
      ; fi

cache:
  directories:
    - $HOME/.tinc/cache
    - $HOME/.stack
